### ISSUE TITLE
Envoy proxy is NOT ready 관련 문제

### ISSUE THREAD

**Issue by HyeyeonKoo** [mojokb/kubeflow-book#6]
안녕하세요~
우선 쿠베플로우 관련 도서를 집필해주신 것에 감사드립니다.

몇 가지를 제외하고는 책에서 주신 가이드를 따라 설치를 진행했습니다.
저는 서버 1대에 마스터 노드만 설치를 진행한 상태입니다.
그런데 *쿠베플로우 대시보드가 로드되지 않아* 질문을 드리고자 합니다. 

제가 가이드를 따라가던 중 변경 또는 추가설치한 부분은 다음과 같습니다.

- nvidia-docker까지는 설치가 잘 된 것 같습니다. (저는 CUDA 11.1 을 사용하고 있기 때문에 `$ sudo docker run --runtime=nvidia --rm nvidia/cuda:11.1-base nvidia-smi`로 명령을 실행했고, 정상적으로 결과를 얻었습니다.)
- 이후 'sudo kubeadm init --pod-network-cidr=192.168.0.0/16'에서 swapoff 에러가 발생해 `sudo swapoff -a`로 설정했고 이후 진행에 이상이 없었습니다.
- nfs가 설치되어있지 않아서 `sudo apt install nfs-common`으로 설치한 후 진행했고, `helm install --name my-release --set nfs.server=127.0.0.1 --set nfs.path=/exported/path stable/nfs-client-provisioner`는 그대로 따라했습니다.
- 이후에 `/etc/hosts`를 설정하는 부분에서 `127.0.0.1    kubeflow-registry.default.svc.cluster.local`로 설정해주었구요.

이렇게 설치한 이후에 클러스터가 구성된 것을 확인했습니다.
![image](https://user-images.githubusercontent.com/43692697/122734513-1b13d780-d2b9-11eb-8480-357a8f50af11.png)

그리고 31380 포트의 LISTEN 상태도 확인했습니다.
![image](https://user-images.githubusercontent.com/43692697/122735289-db99bb00-d2b9-11eb-8970-a740febdce01.png)

그런데, `http://127.0.0.1:31380`으로 접속하려고 하니 connection refused error가 발생했습니다. (방화벽은 열려있습니다.)
계속 원인을 찾다가 `k9s`에서 Crash를 발견했고,
![image](https://user-images.githubusercontent.com/43692697/122735007-92e20200-d2b9-11eb-8211-b538a0b16bfa.png)
로그를 보니 계속해서 `Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected` 에러가 발생하고 있었습니다.
![image](https://user-images.githubusercontent.com/43692697/122735061-a42b0e80-d2b9-11eb-94cc-6c13c383d9e6.png)

원인을 찾아서 해결해보려고 했는데.. 도저히 해결이 되지 않아 질문을 드립니다.  도움을 부탁드립니다. ㅜㅜ

**Comment by mojokb** [comment]
안녕하세요! 책 구매해주셔서 감사합니다.
혹시 제가 환경을 원격이라도 볼 수 있을까요 뭐 예를들어 팀뷰어라던지 ^^
그리고
쿠베플로우 버전과 dex 버전으로 설치하신건지 아니면 istio 버전인지를 알려주시면 더 좋을꺼 같아요 ^^

감사합니다.

2021년 6월 21일 (월) 오후 5:56, HyeyeonKoo ***@***.***>님이 작성:

**Comment by HyeyeonKoo** [comment]
답변 감사합니다.
제가 SSH 환경 접속정보를 드리겠습니다.
아무래도 보안 문제가 있다보니.. 프로필에 기재해주신 메일로 송부드릴게요!

kubeflow 1.0 설치했고, istio 버전으로 설치했습니다!
감사합니다. :)

**Comment by HyeyeonKoo** [comment]
앗 실수로 이슈를 클로징 해버렸네요
